services:
    zen_locale.activelanguagestoparams:
        class: ZEN\LocaleBundle\Listener\ActiveLanguages
        arguments: [@service_container]
        tags:
        - { name: kernel.event_listener, event: kernel.request, method: defineLanguagesInParams }
        
