<?php

namespace ZEN\LocaleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaRepository extends EntityRepository
<<<<<<< HEAD
{   
=======
{
>>>>>>> 137ee28e6debf00dc7b350c71a5511e295db9fd4
}
