<?php

namespace ZEN\LocaleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
    /**
     * Fonction qui retourne les villes ayant au moins la population passée en paramètre
     * @param type $nbPopulationMin 
     * @return type
     */
    public function getMostPopulateCity($nbPopulationMin, $limit){

        return $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.population > :nbMax')
                ->orderBy('c.population','DESC')
                ->getQuery()
                ->setParameter('nbMax', $nbPopulationMin)
                ->setMaxResults($limit)
                ->getResult();
    }
    
    public function getCityByName($name){
        if ($name) {
            $qb = $this->createQueryBuilder('c')
                        ->select('c');
            return $qb->where('c.name LIKE :name')
                        ->setParameter('name', '%'.$name.'%')
                        ->getQuery()
                        ->getOneOrNullResult();
        }  else {
            return null;
        }
        
    }
    
}
