<?php

namespace ZEN\LocaleBundle\Entity;

use ZEN\LocaleBundle\Entity\Translation\TranslatableRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends TranslatableRepository
{
    public function find($id,$locale = null)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.id=:id')
            ->setParameter('id', $id)
            ->innerJoin('e.currency', 'c','WITH','c.id=e.currency')
            ->addSelect('c')
                
            ;
        return $this->getSingleResult($qb,$locale);
    }
    
}
