<?php

namespace ZEN\LocaleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentRepository extends EntityRepository
{
<<<<<<< HEAD
    public function getDepartmentByZipCode($zipCode) {
        
        $qb = $this->createQueryBuilder('d')
                    ->select('d');
        $sub2 = substr($zipCode,0,2);
        $sub3 = substr($zipCode,0,3);
        
        if ($sub2 == '20') {
            $qb->where('d.code = :corseCode')
            ->setParameter('corseCode', '2A');
        }elseif($sub3 == '971' || $sub3 == '972' || $sub3 == '973' || $sub3 == '974' || $sub3 == '976') {
            $qb->where('d.code LIKE :zipCode')
            ->setParameter('zipCode', $sub3);
        }else {
            $qb->where('d.code LIKE :zipCode')
            ->setParameter('zipCode', $sub2);
        }
        return $qb->getQuery()
                ->getOneOrNullResult();    
    }
    
=======
>>>>>>> 137ee28e6debf00dc7b350c71a5511e295db9fd4
}
