<?php

namespace ZEN\LocaleBundle\Entity;

use Doctrine\ORM\EntityRepository;
use ZEN\LocaleBundle\Entity\Translation\TranslatableRepository;
/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends TranslatableRepository
{
}
